### ISSUE TITLE
Suggestions for some parameters, mainly distortion and timing

### ISSUE THREAD

**Issue by h-fehlis** [SMPTE/ris-osvp-metadata-camdkit#122]
I would like to propose some minor changes to the fields for tracking parameters, in particular for the _"distortion"_ and _"timing"_ objects.

**Lens distortion:** In order to allow different lens distortion models in the future, we discussed **not** storing the parameters like this:

```
"lens": {
  "distortion": {
    "radial": { ... }
    "tangential": { ... }
  }
  "undistortion": {
    "radial": { ... }
    "tangential": { ... }
  }
}
```

but rather like this:

```
"lens": {
  "distortion": {
    "Brown-Conrady D-U": {
      "radial": { ... }
      "tangential": { ... }
    }
    "Brown-Conrady U-D": {
      "radial": { ... }
      "tangential": { ... }
    }
  }
}
```

Here, the _"D-U"_ (distorted-to-undistorted) direction is the one following the current OpenLensIO model, the _"U-D"_ direction (undistorted-to-distorted) direction is used by OpenCV. Other distortion models can later be added in the _"distortion"_ object along with the Brown-Conrady parameters.

The documentation currently lists the two parameters:
_"lens"->"distortion"->"distortionOverscan"_ and _"static"->"lens"->"distortionOverscanMax"_ - are the not the same? Or phrased differently: is the overscan parameter that changes every frame actually helpful? If the parameter is supposed to be static, we need to differentiate according to distortion model again:

```
"static": {
  "lens": {
    "distortionOverscanMax": {
      "Brown-Conrady D-U": 1.2,
      "Brown-Conrady U-D": 1.3
    }
  }
}
```

Similarly, if this is not a static parameter, it would have to be included in _"lens"->"distortion"->"Brown-Conrady D-U"_ and _"lens"->"distortion"->"Brown-Conrady U-D"_.

**Timing:** Can we rename _"timing"->"timecode"->"oddField"_ to _"firstField"_ for interlaced video? It is not clear if the odd field of a frame is sent before or after the even field of the same frame. This is for timing only, so it is not important which lines in the frame are being transported, only if the tracking data belongs to the earlier or the later field. ST2110-10 also speaks of RTP timestamps for "first field" and "second field" (section 7.6).

Even better, can we use an integer number _"field"_ (or _"sub-frame"_ or _"sample"_?) instead of the boolean _"oddField"_? Imagine a 30 Hz interlaced video signal (60 fields per second) and a tracking system that runs at 120 Hz. Here, we would like to label the samples 0, 1, 2 and 3 because there are even 4 samples per frame.

Do we need _"timing"->"timecode"->"format"->"dropFrame"_?
A drop frame timecode is present if and only if the denominator _"timing"->"timecode"->"format"->"frameRate"->"denom"_ equals 1001, so this information can be derived from this other parameter.

There seem to be four(!) parameters which specify a frame rate: _"timing->frameRate"_, _"timing"->"timecode"->"format"->"frameRate"_, _"timing"->"synchronization"->"frequency"_ and _"static"->"camera"->captureFrameRate"_. What are they exactly for? I understand that the frequency of tracking samples (is it _"timing->frameRate"_?) can be different from the video frame rate (is it _"timing"->"timecode"->"format"->"frameRate"_?) but what do we need the other two for?

**Protocol:** The value in parameter _"protocol"->"version"_ is a string of format "x.y.z" which needs to be parsed into integer numbers x, y and z to make any version comparisons (sorting strings lexicographically does not work) and this parsing needs to be done for every single tracking packet. Would it not be easier to store x, y, z values as a JSON array directly? So "x.y.z" becomes [x, y, z] with z being optional (or y and z together being optional), so 0 is assumed for any missing number if the array is shorter than 3 elements.

**Transforms:** Could _"transforms"->"transformId"_ just be be _"transforms"->"ID"_ and
_"transforms"->"parentTransformId"_ be _"transforms"->"parentID"_ because the "transform" part is clear?

**Comment by h-fehlis** [comment]
Thank you @jamesmosys !
One more question: I assume that sooner or later somebody (most likely a lens manufacturer) will want to transmit distortion data following a different model (using a "model": "whatever" entry). But in this case, they might also want to send data in "our" Brown-Conrady model (maybe with less accuracy?) to allow old receivers who don't know about this new model yet to be able to deal with lens distortion nevertheless. That will not be possible then, right? I guess it would require a potentially non-backwards compatible change in the protocol which would make it unreadable by old receivers as well. Or it would require a "whatever distortion" entry in addition to the "distortion" entry, which would be a bit ugly, I think. Would it really be a can of worms if somebody could send distortion data using several different models at the same time and the receiver picks what it wants?
If you don't want to change it: "Brown-Conrady D-U" was meant to describe how to get from distorted (D) to undistorted (U) coordinates (in other words: how to undistort a point), so this should go in the "undistortion" section and "Brown-Conrady U-D" should go in the "distortion" section because it describes how to distort a point, right?

**Comment by JGoldstone** [comment]
A question on distortion_overscan, undistortion_overscan, distortion_overscan_max and undistortion_overscan_max: are those floating-point values always strictly positive? Or even always strictly greater than 1.0?

**Comment by h-fehlis** [comment]
All the overscan values are larger than or equal to 1.0. Think of them as a factor to scale up the image sensor size by. Scaling down the image sensor size should never be necessary but if we want to not rule out some very unusual lenses then we could just enforce the condition that the overscan values are always larger than 0.0.

**Comment by jamesmosys** [comment]
See https://github.com/SMPTE/ris-osvp-metadata-camdkit/issues/127#issuecomment-2539332347 for response on distortion. On overscan params I will add the restraints you suggest in my current 0.9.1 PR

**Comment by jamesmosys** [comment]
Resolved in https://github.com/SMPTE/ris-osvp-metadata-camdkit/pull/125
