### ISSUE TITLE
Should timecode maxes out at 30FPS?

### ISSUE THREAD

**Issue by JGoldstone** [SMPTE/ris-osvp-metadata-camdkit#129]
With the changes made to ST 331 this past year (try DuckDuckGo as a search engine and search for "SMPTE ST 331 Amendment 1") it's possible for the SDTI-CP to support up to 120FPS. I don't know of anyone who's shooting at that rate for virtual production, but still. Should we make provision for other than "classic" SMPTE ST 12-1 timecode?

**Comment by jamesmosys** [comment]
Agreed - I will fix in my current PR

**Comment by jamesmosys** [comment]
Resolved in https://github.com/SMPTE/ris-osvp-metadata-camdkit/pull/125
