### ISSUE TITLE
serialization of Timecode to JSON should produce subFrame, not sub_frame

### ISSUE THREAD

**Issue by JGoldstone** [SMPTE/ris-osvp-metadata-camdkit#132]
Our canonical JSON uses mixedCase (lowercase camel case) for attributes throughout, and we are remarkably consistent about it. But `TimingTimecode` fails to maintain this. The `frameRate` in the generated JSON and in the schema is compliant with our convention, but the `sub_frame` is not. Both `TimingTimecode.to_json()` and `TimingTimecode.make_json_schema()` should be changed to be compliant, emitting and specifying, respectively, `subFrame`.

**Comment by jamesmosys** [comment]
Resolved in https://github.com/SMPTE/ris-osvp-metadata-camdkit/pull/125
