### ISSUE TITLE
Spreadsheet uses "Frame Rate," but CAMDKIT uses "FPS." 

### ISSUE THREAD

**Issue by j-helman** [SMPTE/ris-osvp-metadata-camdkit#76]
Which do we want?

**Comment by repentsinner** [comment]
Frame rate is a parameter, FPS is a colloquially (mis)used unit within production, since nobody seems to like the SI unit of Hertz?

https://github.com/sandflow/camdkit/blob/089332958fdac0247088eb3df4a02dbd5e422c21/src/main/python/camdkit/model.py#L51-L56

**Comment by j-helman** [comment]
Overlaps with Pull Request #70 SMPTE ST 2065-4 harmonization.

**Comment by jamesmosys** [comment]
This has been resolved as part of the OpenTrackIO PR. Frame-rate used throughout as discussed.
