### ISSUE TITLE
Clean up a few small typos

### ISSUE THREAD

**Issue by JGoldstone** [SMPTE/ris-osvp-metadata-camdkit#88]
`framework.py`:
"onlyu" -> "only"
"a integer" -> "an integer"

`model.py`:
`StrictlyPostiveRationalParameter` -> `StrictlyPositiveRationalParameter`

`test_cooke_data.py`:
"RED camera reader tests" -> "Cooke lens reader tests"

`test_model.py`:
"RED camera reader tests" -> "Generic camera model tests"

`test_bmd_reader.py`:
"Blackmagic RAW reader tests" -> "Blackmagic camera RAW reader tests"

**Comment by palemieux** [comment]
Moving `StrictlyPostiveRationalParameter -> StrictlyPositiveRationalParameter` to #96
