### ISSUE TITLE
Scope of uniqueness of cameraSerialNumber and lensSerialNumber needs clarification

### ISSUE THREAD

**Issue by JGoldstone** [SMPTE/ris-osvp-metadata-camdkit#93]
Currently for both `cameraSerialNumber` and `lensSerialNumber`, the docstrings simply say "Unique identifier of the camera" or "Unique identifier of the lens". This could be interpreted as saying cameraSerialNumber, e.g., needs to be globally unique. In fact, the cameraSerialNumber only needs to be unique in the context of the camera make and camera model, and the lens serial number only needs to be unique in the context of the lens make and lens model.

**Comment by palemieux** [comment]
>  In fact, the cameraSerialNumber only needs to be unique in the context of the camera make and camera model, and the lens serial number only needs to be unique in the context of the lens make and lens model.

I think these would be good clarifications.

**Comment by JGoldstone** [comment]
This is now pull request #94
